[package]
name = "test_grpc_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tondi-dashboard-core = { path = "../core" }
tondi-rpc-core = { git = "ssh://git@github.com/AvatoLabs/Tondi.git", branch = "taproot" }
