#!/bin/bash

echo "🔧 验证Tondi Dashboard gRPC配置"
echo "================================"
echo ""

echo "1. 检查dashboard配置..."
echo "请确认以下配置："
echo ""
echo "📋 必需配置："
echo "   ✅ Network: Devnet"
echo "   ✅ Enable gRPC: 必须勾选"
echo "   ✅ gRPC Network Interface: Custom"
echo "   ✅ Custom Address: 127.0.0.1:16610 (本地绑定)"
echo "   ✅ Devnet Custom URL: 8.210.45.192:16610 (远程节点)"
echo ""

echo "2. 配置说明..."
echo "🔍 Custom Address (127.0.0.1:16610):"
echo "   - 这是dashboard本地绑定的地址"
echo "   - dashboard会在这个地址上启动gRPC客户端"
echo ""
echo "🔍 Devnet Custom URL (8.210.45.192:16610):"
echo "   - 这是远程Tondi节点的地址"
echo "   - dashboard会连接到这个地址获取数据"
echo ""

echo "3. 常见配置错误..."
echo "❌ 错误1: Custom Address设置为远程地址"
echo "   原因: dashboard无法绑定到远程地址"
echo "   正确: 应该设置为本地地址 (127.0.0.1:16610)"
echo ""
echo "❌ 错误2: Devnet Custom URL为空"
echo "   原因: dashboard不知道连接到哪个节点"
echo "   正确: 应该设置为远程节点地址 (8.210.45.192:16610)"
echo ""
echo "❌ 错误3: Enable gRPC未勾选"
echo "   原因: dashboard不会使用gRPC协议"
echo "   正确: 必须勾选Enable gRPC"
echo ""

echo "4. 验证步骤..."
echo "1. 重启dashboard"
echo "2. 检查日志中是否有gRPC连接信息"
echo "3. 查看是否有错误信息"
echo "4. 确认metrics数据是否显示"

echo ""

echo "5. 如果仍有问题..."
echo "请检查dashboard日志，寻找以下信息："
echo "   - 'gRPC' 相关的日志"
echo "   - 连接错误信息"
echo "   - metrics相关的错误"

echo ""

echo "🎯 配置验证完成！请根据上述要求检查您的配置。"
echo "=================================="
